;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-region
        end-of-region
        mc/goto-end-of-region
        mc/mark-all-like-this-dwim
        tm/pair-backspace
        typopunct-insert-ellipsis-or-middot
        typopunct-insert-typographical-dashes
        ))

(setq mc/cmds-to-run-once
      '(
        typopunct-insert-mp
        ))
