;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-delete-region
        end-of-region
        my-emacs-lisp-open-line
        smart-tab
        sp-cua-replace-region
        sp-wrap-cancel
        sp-wrap-tag-done
        tm/pair-backspace
        tm/pair-insert
        typopunct-insert-ellipsis-or-middot
        typopunct-insert-typographical-dashes
        ))

(setq mc/cmds-to-run-once
      '(
        eval-and-replace
        handle-switch-frame
        mc/mark-all-like-this-dwim
        typopunct-insert-mp
        ))
