;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-cut-region
        cua-delete-region
        cua-paste
        end-of-region
        eval-defun
        eval-expression
        keyboard-escape-quit
        kill-region
        kill-visual-line
        my-back-to-indentation-or-beginning
        my-emacs-lisp-open-line
        my-end-of-code-or-line
        my-newline
        my-smart-downcase-word
        org-beginning-of-line
        org-end-of-line
        smart-tab
        sp--cua-replace-region
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-backward-up-sexp
        sp-cua-replace-region
        sp-emit-sexp
        sp-forward-barf-sexp
        sp-forward-sexp
        sp-join-sexp
        sp-kill-sexp
        sp-remove-active-pair-overlay
        sp-select-next-thing
        sp-select-next-thing-exchange
        sp-self-insert-command
        transpose-sexps
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        beautify-smex
        beginning-of-buffer
        eval-and-replace
        handle-switch-frame
        haskell-indentation-delete-backward-char
        kill-this-buffer
        mc/mark-all-like-this-dwim
        typopunct-insert-mp
        winner-undo
        ))
