(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-output-view-style (quote (("^dvi$" ("^landscape$" "^pstricks$\\|^pst-\\|^psfrag$") "%(o?)dvips -t landscape %d -o && gv %f") ("^dvi$" "^pstricks$\\|^pst-\\|^psfrag$" "%(o?)dvips %d -o && gv %f") ("^dvi$" ("^\\(?:a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4\\)$" "^landscape$") "%(o?)yap %dS -paper a4r -s 0 %d") ("^dvi$" "^\\(?:a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4\\)$" "%(o?)yap %dS -paper a4 %d") ("^dvi$" ("^\\(?:a5\\(?:comb\\|paper\\)\\)$" "^landscape$") "%(o?)yap %dS -paper a5r -s 0 %d") ("^dvi$" "^\\(?:a5\\(?:comb\\|paper\\)\\)$" "%(o?)yap %dS -paper a5 %d") ("^dvi$" "^b5paper$" "%(o?)yap %dS -paper b5 %d") ("^dvi$" "^letterpaper$" "%(o?)yap %dS -paper us %d") ("^dvi$" "^legalpaper$" "%(o?)yap %dS -paper legal %d") ("^dvi$" "^executivepaper$" "%(o?)yap %dS -paper 7.25x10.5in %d") ("^dvi$" "." "%(o?)yap %dS %d") ("^pdf$" "." "gsview32 -remote %s -raise %o %(outpage)") ("^html?$" "." "netscape %o"))))
 '(ahk-bin "d:\\progs\\AutoHotkey\\AutoHotkey.exe")
 '(ahk-syntax-directory "d:/progs/AutoHotkey/Extras/Editors/Syntax/")
 '(ange-ftp-ftp-program-name "d:\\progs\\ftp.exe")
 '(ansi-color-names-vector ["#212526" "#ff4b4b" "#b4fa70" "#fce94f" "#729fcf" "#ad7fa8" "#8cc4ff" "#eeeeec"])
 '(background-color "#002b36")
 '(background-mode dark)
 '(blink-cursor-mode nil)
 '(blink-matching-paren nil)
 '(bmkp-last-as-first-bookmark-file "c:\\Users\\Matus\\AppData\\Roaming\\.emacs.d\\bookmarks")
 '(bookmark-version-control t)
 '(calc-settings-file "~\\.emacs.d\\my-calc.el")
 '(cua-enable-cua-keys nil)
 '(cursor-color "#839496")
 '(custom-enabled-themes (quote (my-tango-dark)))
 '(custom-safe-themes (quote ("18b79c737a005b87246232739c5cd21aab19f8c15f3a822d64b8cbb8dbbc8525" "9eb325147f82880372869ae998bd6c93adb34fc80b1b5cb2976744fb4dc73cb7" "32807962da64511b0529913b8fc19d527b7bc1d32e6dc298066e53e5d67de571" default)))
 '(custom-theme-directory "~/.emacs.d/themes/")
 '(cycbuf-buffer-sort-function (quote cycbuf-sort-by-recency))
 '(desktop-buffer-filter (quote my-desktop-filter))
 '(desktop-save t)
 '(exec-path (quote ("d:/progs/gnuutils/bin/" "c:/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0/" "d:/progs/MiKTeX/miktex/bin/" "D:/progs/Git/cmd" "D:/progs/TortoiseHg/" "d:/progs/Aspell/bin/" "C:/Users/Matus/AppData/Roaming/MiKTeX/2.9/miktex/bin/" "d:/progs/emacs-24.1/bin")))
 '(foreground-color "#839496")
 '(global-undo-tree-mode t)
 '(golden-ratio-exclude-buffer-names (quote ("*helm kill-ring*")))
 '(ibuffer-fontification-alist (quote ((10 buffer-read-only font-lock-constant-face) (15 (and buffer-file-name (string-match ibuffer-compressed-file-name-regexp buffer-file-name)) font-lock-doc-face) (20 (string-match "^*" (buffer-name)) font-lock-keyword-face) (25 (and (string-match "^ " (buffer-name)) (null buffer-file-name)) italic) (30 (memq major-mode ibuffer-help-buffer-modes) font-lock-comment-face) (35 (memq major-mode (quote (dired-mode sr-mode))) font-lock-function-name-face))))
 '(ibuffer-show-empty-filter-groups t)
 '(ido-ubiquitous-command-compatibility-exceptions (quote (ibuffer-switch-to-saved-filter-groups)))
 '(ido-ubiquitous-command-exceptions (quote (smex-major-mode-commands beautify-smex ido-goto-symbol grep-read-files diredp-dired-files)))
 '(ido-ubiquitous-enable-compatibility t)
 '(ido-ubiquitous-function-exceptions (quote (diredp-dired-files-interactive-spec)))
 '(ido-ubiquitous-mode t)
 '(imenu-auto-rescan t)
 '(indicate-empty-lines nil)
 '(ispell-personal-dictionary "~/.emacs.d/.ispell")
 '(ispell-program-name "d:\\progs\\Aspell\\bin\\aspell.exe")
 '(ls-lisp-dirs-first t)
 '(markdown-link-space-sub-char "-")
 '(preview-gs-command "gswin64c.exe")
 '(preview-scale-function 1.8)
 '(safe-local-variable-values (quote ((eval allout-mode t))))
 '(sp-autoescape-string-quote-if-empty (quote (python-mode)))
 '(sp-ignore-modes-list (quote (image-dired-display-image-mode image-dired-thumbnail-mode)))
 '(sp-navigate-consider-symbols t)
 '(sr-attributes-display-mask (quote (nil nil nil nil t t t)))
 '(sr-listing-switches "-alh")
 '(sr-popviewer-enabled nil)
 '(sr-show-file-attributes nil)
 '(sr-tabs-max-tabsize 18)
 '(sr-traditional-other-window nil)
 '(sr-windows-locked nil)
 '(text-mode-hook (quote (text-mode-hook-identify))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bmkp-local-directory ((t (:inherit dired-directory))))
 '(cycbuf-current-face ((t (:inherit hl-line))))
 '(cycbuf-header-face ((t (:inherit font-lock-type-face))))
 '(diredp-dir-priv ((t (:inherit dired-directory))))
 '(diredp-exec-priv ((t nil)))
 '(diredp-file-name ((t (:inherit default))))
 '(diredp-ignored-file-name ((t (:inherit shadow))))
 '(diredp-link-priv ((t nil)))
 '(diredp-no-priv ((t nil)))
 '(diredp-number ((t (:inherit default))))
 '(diredp-other-priv ((t nil)))
 '(diredp-rare-priv ((t nil)))
 '(diredp-read-priv ((t nil)))
 '(diredp-write-priv ((t nil)))
 '(sp-pair-overlay-face ((t (:background "#004a5d")))))
(put 'narrow-to-region 'disabled nil)
(put 'narrow-to-page 'disabled nil)
(put 'set-goal-column 'disabled nil)
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
