(require 'sunrise-x-loop)
(require 'sunrise-x-mirror)
(require 'sunrise-x-modeline)
(require 'sunrise-x-tabs)
(require 'sunrise-x-w32-addons)

(defun my-sunrise-init ()
  (define-key sr-mode-map [(backspace)] 'sr-dired-prev-subdir)
  (define-key sr-mode-map (kbd "M-\r") 'dired-w32-browser)
  (sr-sort-by-extension)
  (golden-ratio-disable)
  (windmove-down)
  (delete-window)
  (balance-windows)
  )
(add-hook 'sr-start-hook 'my-sunrise-init)

(defun my-sunrise-deinit ()
  (golden-ratio-enable))
(add-hook 'sr-quit-hook 'my-sunrise-deinit)
